# https://github.com/hvr/multi-ghc-travis

env:
 - GHCVER=7.8.4 CABALVER=1.22

before_install:
 - travis_retry wget -O - http://llvm.org/apt/llvm-snapshot.gpg.key|sudo apt-key add -
 - travis_retry sudo add-apt-repository -y ppa:hvr/ghc
 - travis_retry sudo apt-get update
 - travis_retry sudo apt-get install cabal-install-$CABALVER ghc-$GHCVER
 - export PATH=/opt/ghc/$GHCVER/bin:/opt/cabal/$CABALVER/bin:$PATH

install:
 - cabal --version
 - echo "$(ghc --version) [$(ghc --print-project-git-commit-id 2> /dev/null || echo '?')]"
 - travis_retry cabal update
 - cabal sandbox init
 - git clone --branch=develop --depth=1 git://github.com/dysinger/amazonka ./.cabal-sandbox/src/amazonka
 - cabal sandbox add-source ./.cabal-sandbox/src/amazonka/core
 - cabal sandbox add-source ./.cabal-sandbox/src/amazonka/amazonka
 - cabal sandbox add-source ./.cabal-sandbox/src/amazonka/amazonka-ec2
 - cabal install --only-dependencies --force-reinstalls

script:
 - cabal check
 - cabal install -v2 --program-suffix=-$(cabal info .|head -n 1|cut -d' ' -f2|cut -d'-' -f2)
 - cabal test
#- cabal haddock
 - cabal sdist
#- export SRC_TGZ=$(cabal info . | awk '{print $2 ".tar.gz";exit}') ;
#  cd dist/;
#  if [ -f "$SRC_TGZ" ]; then
#     cabal install --force-reinstalls "$SRC_TGZ";
#  else
#     echo "expected '$SRC_TGZ' not found";
#     exit 1;
#  fi
