# https://github.com/hvr/multi-ghc-travis

env:
 - GHCVER=7.8.4 CABALVER=1.20 LLVMVER=3.4

before_install:
 - travis_retry wget -O - http://llvm.org/apt/llvm-snapshot.gpg.key|sudo apt-key add -
 - echo "deb http://llvm.org/apt/precise/ llvm-toolchain-precise-$LLVMVER main"
    | sudo tee /etc/apt/sources.d/llvm.list
 - travis_retry sudo add-apt-repository -y ppa:hvr/ghc
 - travis_retry sudo apt-get update
 - travis_retry sudo apt-get install cabal-install-$CABALVER ghc-$GHCVER llvm-$LLVMVER
 - export PATH=/opt/ghc/$GHCVER/bin:/opt/cabal/$CABALVER/bin:$PATH

install:
 - cabal --version
 - echo "$(ghc --version) [$(ghc --print-project-git-commit-id 2> /dev/null || echo '?')]"
 - travis_retry cabal update
 - cabal sandbox init
 - cabal install -j -fllvm -v2 --enable-tests --enable-benchmarks --enable-documentation
     --force-reinstalls --only-dependencies --enable-split-objs

script:
 - cabal install -j -fllvm -v2 --enable-tests --enable-benchmarks --enable-documentation
 - cabal test
 - cabal check
#- cabal haddock
 - cabal sdist
#- export SRC_TGZ=$(cabal info . | awk '{print $2 ".tar.gz";exit}') ;
#  cd dist/;
#  if [ -f "$SRC_TGZ" ]; then
#     cabal install --force-reinstalls "$SRC_TGZ";
#  else
#     echo "expected '$SRC_TGZ' not found";
#     exit 1;
#  fi
