# https://github.com/hvr/multi-ghc-travis

env:
 - CABALVER=1.22 GHCVER=7.10.1

before_install:
 - travis_retry sudo add-apt-repository -y ppa:hvr/ghc
 - travis_retry sudo apt-get update
 - travis_retry sudo apt-get install cabal-install-$CABALVER ghc-$GHCVER llvm
 - export PATH=/opt/ghc/$GHCVER/bin:/opt/cabal/$CABALVER/bin:$PATH

install:
 - cabal --version
 - echo "$(ghc --version) [$(ghc --print-project-git-commit-id 2> /dev/null || echo '?')]"
 - travis_retry cabal update
 - cabal sandbox init
 - git clone --branch=develop --depth=1 git://github.com/dysinger/amazonka ./.cabal-sandbox/src/amazonka
 - cabal sandbox add-source ./.cabal-sandbox/src/amazonka/core
 - cabal sandbox add-source ./.cabal-sandbox/src/amazonka/amazonka
 - cabal sandbox add-source ./.cabal-sandbox/src/amazonka/amazonka-ec2
 - if ! cabal install --enable-split-objs --enable-library-stripping --only-dependencies --ghc-options='-fllvm -static -threaded -rtsopts -eventlog -debug' ; then
     cat .cabal-sandbox/logs/*.log ;
     exit 1 ;
   fi

script:
 - cabal install -v2 --enable-split-objs --enable-executable-stripping --enable-tests --enable-benchmarks --program-suffix=-$(cabal info .|head -n 1|cut -d' ' -f2|cut -d'-' -f2)-$(git log HEAD~1..HEAD --pretty=%h) --ghc-options='-fllvm -static -threaded -rtsopts -eventlog -debug'
 - cabal test
 - cabal check
 - cabal haddock
 - cabal sdist
 - export SRC_TGZ=$(cabal info . | awk '{print $2 ".tar.gz";exit}') ;
   cd dist/;
   if [ -f "$SRC_TGZ" ]; then
      cabal install --force-reinstalls "$SRC_TGZ";
   else
      echo "expected '$SRC_TGZ' not found";
      exit 1;
   fi
 - cabal install
