resolver: lts-6.0 # OR nightly-2016-06-05
packages:
  - '.'
  - location:
      git: https://github.com/brendanhay/amazonka.git
      commit: 73e1d4ba20377e94048939dbb7e673fd7e5b2a1d
    extra-dep: true
    subdirs:
      - amazonka
      - amazonka-ec2
      - core
extra-deps:
  - git-embed-0.1.0
  - unordered-containers-0.2.7.0
