resolver: lts-6.6 # OR nightly-2016-07-05
packages:
- '.'
# # NOTE: Uncomment to work on the latest amazonka master
# - location:
#     git: https://github.com/brendanhay/amazonka.git
#     commit: master
#   extra-dep: true
#   subdirs:
#   - amazonka
#   - amazonka-ec2
#   - core
extra-deps:
- git-embed-0.1.0
stack:
  images:
  - name: dysinger/rifactor
    base: dysinger/ubuntu-with-libgmp:16.04
