resolver: lts-6.2 # OR nightly-2016-06-05
packages:
- '.'
# # NOTE: Uncomment to work on the latest amazonka master
# - location:
#     git: https://github.com/brendanhay/amazonka.git
#     commit: master
#   extra-dep: true
#   subdirs:
#   - amazonka
#   - amazonka-ec2
#   - core
extra-deps:
- amazonka-1.4.3
- amazonka-core-1.4.3
- amazonka-ec2-1.4.3
- git-embed-0.1.0
- unordered-containers-0.2.7.0
