#-*- mode:conf; -*-

FROM docker.knewton.net/knewton/rifactor:lib
MAINTAINER Tim Dysinger <tim@knewton.com>

ADD rifactor /usr/local/bin/rifactor

VOLUME /etc/rifactor
ENTRYPOINT /usr/local/bin/rifactor
